services:
  postgres:
    image: postgres:16
    container_name: url-shortener-pg
    restart: always
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: agustin
      POSTGRES_PASSWORD: localhost19
      POSTGRES_DB: url_shortener_db
    volumes:
      - ./init:/docker-entrypoint-initdb.d
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
